MODEL_PATH = "assets/models/face_landmarker.task"
OVERLAYS_DIR = "assets/overlays"
DEFAULT_OVERLAY_FILENAME = "mask.png"

CAMERA_INDEX = 0
FRAME_WIDTH = 960
FRAME_HEIGHT = 720

MAX_NUM_FACES = 1

WINDOW_NAME = "SnapFace Filter"
CONTROL_WINDOW_NAME = "Controls"

DEFAULT_SHOW_LANDMARKS = 1
DEFAULT_SHOW_ANCHORS = 1
DEFAULT_SHOW_OVERLAY = 1
DEFAULT_OVERLAY_SCALE = 100

MIN_SCALE_PERCENT = 50
MAX_SCALE_PERCENT = 180

DEFAULT_WARP_MODE = 0  # 0 auto, 1 affine, 2 triangle
DEFAULT_COMPARE_MODE = 0  # 0 off, 1 side-by-side

SMOOTHING_MIN_ALPHA = 0.18
SMOOTHING_MAX_ALPHA = 0.72
SMOOTHING_MOTION_SCALE = 18.0
POSE_BLEND = 0.35

FACE_MASK_SHRINK = 0.93
FACE_MASK_BLUR = 17
OCCLUSION_EDGE_THRESHOLD1 = 80
OCCLUSION_EDGE_THRESHOLD2 = 160
OCCLUSION_DILATE = 2
OCCLUSION_STRENGTH = 0.45

LEFT_EYE_OUTER = 33
RIGHT_EYE_OUTER = 263
MOUTH_LEFT = 61
MOUTH_RIGHT = 291
NOSE_TIP = 1
CHIN = 152